# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('listing_url', models.URLField(max_length=512)),
                ('title', models.CharField(max_length=256)),
                ('sale_type', models.IntegerField(choices=[(0, 'Auction'), (1, 'BuyItNow')], default=0, null=True)),
                ('condition', models.IntegerField(choices=[(0, 'Used'), (1, 'New')], default=0, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('seller_user_id', models.CharField(max_length=64)),
                ('bid_count', models.IntegerField(default=0, null=True)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('start_price_currency', models.CharField(max_length=3, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('current_price_currency', models.CharField(max_length=3, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('shipping_cost_currency', models.CharField(max_length=3, null=True)),
                ('buyitnow_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('buyitnow_price_currency', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
