# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField(default=0, null=True)),
                ('availability', models.CharField(max_length=64, null=True)),
                ('brickset_url', models.URLField(max_length=512, null=True)),
                ('image_url', models.URLField(max_length=512, null=True)),
                ('rrp_gbp', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='UK RRP (\xa3)')),
                ('rrp_usd', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='US RRP ($)')),
                ('rrp_eur', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='EU RRP (\u20ac)')),
            ],
        ),
    ]
