# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='CatalogSet',
        ),
    ]
